#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code and counts occurrences

awk '{count[$1" "$9]++} END {for (key in count) printf "%d %s\n", count[key], key}' apache-access.log | sort -nr
