#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code and counting

awk 'NF >= 9 && $1 ~ /^[0-9.]+$/ && $9 ~ /^[0-9]{3}$/ {
    count[$1" "$9]++
}
END {
    for (k in count)
        print count[k], k
}' "$1" | sort -k1,1nr -k2,2r -k3,3r
