#!/usr/bin/env bash
#clock navigatioin
hour=0

while [ $hour -le 12 ]   # OUTER LOOP (hours)
do
    echo "Hour: $hour"

    minute=1             # reset minutes EACH time

    while [ $minute -le 59 ]   # INNER LOOP (minutes)
    do
        echo "$minute"
        minute=$((minute + 1))
    done

    hour=$((hour + 1))    # go to next hour
done

