#!/usr/bin/env bash
#clock navigation

hour=0
minute=1

while [ $hour -le 12 ]
do
    printf "%02d:%02d\n" "$hour" "$minute"

    minute=$((minute + 1))

    if [ $minute -gt 59 ]; then
        minute=1
        hour=$((hour + 1))
    fi
done

