#!/usr/bin/env bash
#terminte script its self
echo $$ > /var/run/myscript.pid
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f /var/run/myscript.pid; exit' SIGQUIT SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2 &
    wait
done
